// Schema Sync Configuration
// This file tracks all tables that should be included in the white-label script
// When adding new tables via migrations, add them here to keep the script in sync

export interface TableDefinition {
  name: string;
  description: string;
  addedAt: string;
  lastUpdated: string;
}

// Registry of all tables in the system
// Update this when creating new tables
export const TABLE_REGISTRY: TableDefinition[] = [
  { name: 'profiles', description: 'User profiles with balance and contact info', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'user_roles', description: 'User role assignments (admin, moderator, user)', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'smm_providers', description: 'SMM API providers configuration', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'imported_services', description: 'Services imported from SMM providers', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'service_customizations', description: 'Custom prices and settings for services', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'category_display_order', description: 'Custom category ordering for UI', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'orders', description: 'User orders', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'refills', description: 'Order refill requests', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'balance_history', description: 'User balance recharge history', addedAt: '2026-01-01', lastUpdated: '2026-01-01' },
  { name: 'support_tickets', description: 'Support ticket system', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'ticket_messages', description: 'Messages for support ticket chat', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'platform_icons', description: 'Social platform icons and settings', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'platform_category_links', description: 'Links between platforms and categories', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'category_icons', description: 'Category emoji/icon assignments', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'landing_content', description: 'Landing page customizable content', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'site_settings', description: 'SEO and site configuration', addedAt: '2024-01-01', lastUpdated: '2026-01-31' },
  { name: 'terms_content', description: 'Terms of service content', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'privacy_content', description: 'Privacy policy content', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'ai_providers', description: 'AI provider configurations', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'ai_agents', description: 'AI agent configurations', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'seo_actions', description: 'SEO automation actions', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'api_keys', description: 'User API keys for external access', addedAt: '2024-01-01', lastUpdated: '2024-12-31' },
  { name: 'favorite_services', description: 'User favorite services', addedAt: '2026-01-02', lastUpdated: '2026-01-02' },
  { name: 'store_frontends', description: 'Public store frontends/landing pages', addedAt: '2026-01-10', lastUpdated: '2026-01-18' },
  { name: 'store_packages', description: 'Store packages for purchase flow', addedAt: '2026-01-10', lastUpdated: '2026-01-18' },
  { name: 'store_orders', description: 'Public store checkout orders', addedAt: '2026-01-10', lastUpdated: '2026-01-18' },
  { name: 'store_payment_intents', description: 'Payment intent records for late reconciliation (kept even if pending orders are deleted)', addedAt: '2026-01-23', lastUpdated: '2026-01-23' },
  { name: 'store_package_credits', description: 'BRL credits per phone+package generated by late-approved payments', addedAt: '2026-01-23', lastUpdated: '2026-01-23' },
  { name: 'store_order_links', description: 'Index of (service_id, link) for duplicate-prevention during checkout', addedAt: '2026-01-20', lastUpdated: '2026-01-20' },
  { name: 'store_menu_banners', description: 'Banners shown in the StoreFront sidebar menu footer', addedAt: '2026-01-26', lastUpdated: '2026-01-26' },
  { name: 'external_database_configs', description: 'Admin-saved external DB connection config', addedAt: '2026-01-19', lastUpdated: '2026-01-19' },
];

// Get table names for quick lookup
export const getTableNames = (): string[] => TABLE_REGISTRY.map(t => t.name);

// Check if a table is registered
export const isTableRegistered = (tableName: string): boolean => 
  TABLE_REGISTRY.some(t => t.name === tableName);

// Reminder message for developers
export const SYNC_REMINDER = `
╔════════════════════════════════════════════════════════════════╗
║  LEMBRETE: Ao criar novas tabelas via migração, atualize:     ║
║  1. src/lib/schemaSync.ts - TABLE_REGISTRY                    ║
║  2. src/lib/databaseSchema.ts - DATABASE_SCHEMA               ║
║  Isso mantém o script white-label sincronizado!               ║
╚════════════════════════════════════════════════════════════════╝
`;

console.log(SYNC_REMINDER);
